baseURL: https://blog.naba.run
languageCode: en-us
title: Nabarun Pal
theme: yinyang
enableEmoji: true
pygmentsCodeFences: true
pygmentsUseClasses: true
params:
  headTitle: Nabarun Pal
  postFooterContent: "Have any feedback? Please reach out to me at &ldquo;hey [at] naba [dot] run&rdquo;"
  mainSections:
    - posts
  socials:
    - name: RSS
      link: /index.xml
    - name: About
      link: https://naba.run
    - name: Github
      link: https://github.com/palnabarun
    - name: LinkedIn
      link: https://linkedin.com/in/palnabarun
