baseURL: https://blog.naba.run
languageCode: en-us
title: Nabarun Pal
theme: yinyang
enableEmoji: true
pygmentsCodeFences: true
pygmentsUseClasses: true
params:
  headTitle: Nabarun Pal
  postFooterContent: "Have any feedback? Please reach out to me at &ldquo;hey [at] naba [dot] run&rdquo;"
  copyrightContent: "&copy; <a href='https://creativecommons.org/licenses/by-nc-sa/2.0/'>CC-BY-NC-SA</a> Nabarun Pal 2020"
  mainSections:
    - posts
  socials:
    - name: Tags
      link: /tags/
    - name: RSS
      link: /index.xml
    - name: About
      link: https://naba.run
    - name: Github
      link: https://github.com/palnabarun
    - name: LinkedIn
      link: https://linkedin.com/in/palnabarun
