baseURL: https://blog.naba.run
languageCode: en-us
title: Nabarun Pal
theme: vitae
copyright: © CC-BY-NC-SA Nabarun Pal
pygmentsstyle: monokai
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
enableEmoji: true
params:
  description: A pragmatic engineer who is constantly learning
  subtitle: A pragmatic engineer who is constantly learning
  keywords:
    - "blog"
    - "technology"
    - "open-source"
    - "opsec"
    - "security"
    - "infrastructure"
  math: true
  mainSections:
    - posts
  social:
    - name: Github
      icon: fab fa-github
      url: https://github.com/palnabarun
    - name: Email
      icon: fas fa-envelope
      url: mailto:hey@naba.run
    # - name: Twitter
    #   icon: fas fa-twitter
    #   url: https://twitter.com/theonlynabarun
    # - name: LinkedIn
    #   icon: fas fa-linkedin
    #   url: https://linkedin.com/palnabarun
    - name: RSS
      icon: fas fa-rss
      url: /index.xml
taxonomies:
  tags: tags
  series: series
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: All Posts
      url: /posts/
      weight: 2
    - name: About
      url: https://nabarun.dev
      weight: 3
    - name: Contact
      url: https://nabarun.dev/contact
      weight: 4
    - name: Tags
      url: /tags/
      weight: 5
